### ISSUE TITLE
Onboarding Designs (initial implementation)

### ISSUE THREAD

**Issue by geffenz** [zcash/secant-android-wallet#11]
The implementation steps for creating the onboarding UI flow are as follows:

 - First launch checks (can happen in parallel with other issues)
     - Add preference infrastructure #13
     - Configure UI to display during first launch
 - Add splash screen (this can happen in parallel with other issues) #14
 - Add launcher icon (this can happen in parallel with other issues) #20
 - Add preference infrastructure #13 (blocks #28)
 - Add SDK integration #28 (blocks #16 and #17)
 - Unstyled onboarding flow — To speed initial implementation, the flow will have the correct layouts but will use default Material components
     1. Introduction #15 
     1. Import a wallet (this is being implemented first, because it'll get us a functional wallet faster) #17
     1. Create a wallet (this will be a medium to large effort and can be broken down into multiple tasks) #16
 - Style onboarding flow #18

**Comment by geffenz** [comment]
@ccjernigan Where should we look to view this build so we can approve this ticket?

**Comment by ccjernigan** [comment]
@geffenz 

Immediately: Each linked issue should have a linked pull request, and each pull request should generally have screenshots attached.

Upcoming: We're working on automated builds that you should be able to install #176 although all the parts aren't completely hooked up yet.

**Comment by pacu** [comment]
Moved this to the corresponding epic "onboarding flow"
