### ISSUE TITLE
[Scaffold] Home/Balance Screen 

### ISSUE THREAD

**Issue by geffenz** [zcash/secant-android-wallet#12]
The home screen has a few design elements, which can be broken into these parts:

1. Navigation (QR/Profile) and info field (status)
2. Balance and circular animations (sync/confirms/etc)
3. Primary/secondary actions
4. Latest (or pending) transactions

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/2bd46bac-c67e-42af-89e8-06b47171329b)

**Comment by ccjernigan** [comment]
@geffenz Why does the request button include the text "ZEC".  Could it be simplified to just "Request"?

**Comment by pacu** [comment]
@geffenz  I don't think we have tickets that capture the fact that the definitive look of this view is still pending to be done
