### ISSUE TITLE
[scaffold] Request ZEC Form

### ISSUE THREAD

**Issue by geffenz** [zcash/secant-android-wallet#135]
As a user I would like to create a payment request so that I can request payments in ZEC and share them through default share channels offered by the operating system or as a QR code on screen

acceptance criteria:
- the request follows the ZIP-321 specification
- The request screen offers the user the ability of displaying it as a QR.
- The request screen form common components with the send form
- The user can opt to send the request as zero-value transaction to a given address through QR code (or address book if available) or pasting it into the recipient textfield.

A followup issue for this is #202, which implements the ability for the app to open these Zec requests.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/e52bf527-eb4c-43dc-ad15-b9ee7a535124)

https://xd.adobe.com/view/5eb728b7-cb5e-46d0-ac4d-5f3369faa82f-0be4/

**Comment by pacu** [comment]
@geffenz wouldn't "create and share" be a better term? Since this form is pretty similar to the send flow, the user might be confused by the word "send"

**Comment by pacu** [comment]
@geffenz How would users requesting ZEC in person to others share the resulting QR code?

**Comment by geffenz** [comment]
Lets change the action to "create and share" which shares only a link. In the future we may have two options "Share as email" or "share as text" so we could create a QR to increase usability.

**Comment by geffenz** [comment]
Great call out with Carter. Let's remove the to field for now, as a user would be selecting their recipient from the share drawer.
