### ISSUE TITLE
[Function] Wallet Details Screen

### ISSUE THREAD

**Issue by geffenz** [zcash/secant-android-wallet#140]
As a user I would like to see my wallet's details so that I can visualize my addresses and viewing keys

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/5e688629-4e71-43ef-9f02-8d4ddc5dfeed)

Designs:
https://xd.adobe.com/view/68ce275c-cab9-42da-9679-08501e961790-3d9d/

Acceptance Criteria:
- Wallet details screen shows:
  - a text representation of the current UA (they are rolled so they could change) that has the first and last 6 characters highlighted for validation purposes
  - a drawer section that can be tapped to show the included receivers in the same fashion, **except orchard**
  - a unified viewing key section that shows that viewing key in the same fashion

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/5e688629-4e71-43ef-9f02-8d4ddc5dfeed)

https://xd.adobe.com/view/68ce275c-cab9-42da-9679-08501e961790-3d9d/

**Comment by pacu** [comment]
@geffenz how about "can receive" instead of "which includes"
