### ISSUE TITLE
[Scaffold] Wallet Details Screen

### ISSUE THREAD

**Issue by geffenz** [zcash/secant-android-wallet#144]
This is the detailed address screen, not the initial profile view.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/a357760c-09f3-4700-86fc-40ab5e7d1847)

**Comment by ccjernigan** [comment]
@geffenz Under the list of addresses, is there a reason "Transparent Address" the only one that ends with the word "Address"?  For consistency, should the word address be dropped there?
