### ISSUE TITLE
Add option to provide wallet birthday during restore

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#151]
The designs have a button for "Add a wallet birthday" to the restore wallet flow, however there's no design for what that button will display to the user.

This issue is to remember to complete the design, then implement the button.

While the app will be functional without this feature, adding it will improve performance of wallet import.

**Comment by geffenz** [comment]
Geffen to add images on birthday entrance during import (and possibly a in-settings update spot).
