### ISSUE TITLE
Improve Ability to Run Application under Robo Test

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#179]
## Is your feature request related to a problem? Please describe.
We'd like to have a "chaos monkey" test that is able to exercise different parts of the app UI.  The problem is that the onboarding flow's onboarding "test" will likely block the robo tester from actually moving forward.

## Describe the solution you'd like
Either:
 - Detect when running under a robo test with the `isUserAMonkey` API and bypass the onboarding test.  I don't know if isUserAMonkey is the right API to check, or whether we should use `FirebaseTestLabUtil. isFirebaseTestLab`
 - Add a robo test script that can fill in the test correctly in order to move forward.

I think the check is better than the robo script, because the check can also work for Google Play prelaunch reports easily.

I think we can inject this check somewhere in the BackupViewModel or the MainActivity.

## Additional context
Robo tests will be run both by our continuous integration scripts, as well as by Google Play prelaunch reports.

The `isUserAMonkey` option is probably easier for forks, as they won't have to manually supply the robo script to Google.  The disadvantage is that a small amount of test coverage is lost, although we already use instrumentation tests to extensively cover the onboarding flow.

It should be possible to test this locally.  Android emulator and adb have a monkeyrunner tool (its different from the robot test, but close enough).

**Comment by HonzaR** [comment]
Hi @ccjernigan, do we want the monkey test runner skips also the Restore Wallet screen (beside the Create Wallet screen)? As the runner probably won't get through this part of the app too.

**Comment by ccjernigan** [comment]
Yes, that's a good idea.

Although that one might require us to re-think the requirements of this issue.  That one is hard to skip (compared to the test).  It would probably mean needing to generate a random seed phrase because otherwise it wouldn't know how to bypass.

**Comment by HonzaR** [comment]
> Yes, that's a good idea.
> 
> Although that one might require us to re-think the requirements of this issue. That one is hard to skip (compared to the test). It would probably mean needing to generate a random seed phrase because otherwise it wouldn't know how to bypass.

Does it really need to be a random seed? Or can we provide just some mock seed like we do in our existing tests? Thank you.
