### ISSUE TITLE
Style Onboarding Flow

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#18]
After the onboarding flow is implemented, go back and apply the UI styling from the designs.

**Comment by geffenz** [comment]
Let's do a review of the style guide and onboard flow and revisit this ticket. It may be a legacy methodology now that we have [Scaffold] & [Funcitonal].

**Comment by geffenz** [comment]
Let's do a review of the style guide and onboard flow and revisit this ticket. It may be a legacy methodology now that we have [Scaffold] & [Funcitonal].

**Comment by geffenz** [comment]
This process is legacy. Design reviews incoming with actual builds.
