### ISSUE TITLE
Throttle Emissions from `WalletViewModel.walletSnapshot`

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#188]
### Describe the issue
The wallet snapshot flow updates very frequently (many times per second) especially during initial synchronization.

#### If so, please list the steps to reproduce below:
1. Add a log message either as an `onEach` on the flow or within the Home composable to make recompositions apparent

### Expected behaviour
Recompositions should be occurring infrequently when there's something useful to display to the user.

### Actual behaviour + errors
Recompositions are happening many times per second.

### Any extra information that might be useful in the debugging process.
A solution would be an operator on the flow to reduce the number of emissions, e.g. reducing update frequency to something on the order of once per second.  We can't use the built-in `throttle` operator, as it has problems with starvation.

The preferred solution would be an operator that:
 - Has a configurable interval
 - Emits immediately if there's a new value there has been no emission.  E.g. (a) comes in at t=0, then a is emitted immediately.
 - Emits immediately if there's been no emission for a reporting interval.  E.g. (a) comes in at t=0, then b comes in at t=2000.  a is emitted at t=0 and b is emitted at t=2000.
 - Drops intermediate values if there are multiple values below the reporting interval.  E.g. (a, b, c) all come in rapidly at t=0 milliseconds, t=100 milliseconds, and t=150 milliseconds.  The reporting interval is 1 second.  Then at t=0 a is emitted and t=1000 milliseconds only c is emitted (b is dropped)

Another solution could be to move the collection of the wallet snapshot object to deeper in the compose tree, so that recompositions happen in a smaller scope.  However we don't want to implement it this way, because it makes the views a lot more complex.

This is a good first issue for someone new to the project.  While implementing the flow operator will be a bit complex, it is also very self-contained and doesn't rely on other parts of our codebase.

**Comment by pacu** [comment]
can you debounce if certain interval of time has not passed?  It's arbitrary and could miss the last update at times depending on timing. But it's a solution to explore
