### ISSUE TITLE
[UI Component] Circular Image w/ badge accessory

### ISSUE THREAD

**Issue by pacu** [zcash/secant-android-wallet#195]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/894741af-5422-4345-9acc-cf0f23f2c674)

see: https://xd.adobe.com/view/4dbf23de-3a0f-46e0-bd6a-1a0138f861bc-18ec/screen/a929090c-5bbd-4c05-a362-9e655de26b84/specs/

**Comment by geffenz** [comment]
Wait for feedback on illustration placement

**Comment by ccjernigan** [comment]
This is being implemented in #593
