### ISSUE TITLE
Add Launcher Icon

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#20]
Once we get the image assets, add a launcher icon to the app.  When implementing this, be sure to update the readme to factor in the need for forks to swap in their own icon.

**Comment by geffenz** [comment]
Waiting on designs from Geffen. Assigning.

**Comment by geffenz** [comment]
Start with simplified SVG (use android tool), and then iterate.

**Comment by geffenz** [comment]
For ios (not this ticket but doesnt exist) lets use appIcon bundle (all sizes).

Let's also include GooglePlay store and App Store.
