### ISSUE TITLE
Scaffold: Add Contact Support Screen

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#213]
## Is your feature request related to a problem? Please describe.
To troubleshoot user support requests, we often need some information about their setup. Users can have a hard time providing this to us accurately.

## Describe the solution you'd like
Add a contact support screen to the app, which can generate an email for users to edit/review before sending to us.  Even though users can edit, we should have defaults configured to be as private/safe as is reasonable.

The types of information that would be useful
- Android version - To troubleshoot issues with specific Android versions
- Device manufacturer - To troubleshoot device-specific issues
- App version - To troubleshoot issues with specific app versions, and to confirm the user has the latest version
- App install time - To understand if this is a new or long-time user, as well as whether we had migration issues from some old prior version.
- Current timestamp - Only useful in relation to other timestamps
- Last reboot timestamp - Identifies the last time the user rebooted.  Useful to identify whether a reboot might help fix the issue (e.g. no reboot in 3 months, then maybe a reboot would help).  Reboots every night at 3am might indicate why WorkManager isn't running because of an OEM autoreboot option.
- App update time - Helps clarify if users say “last update broke the app”
- WorkManager run history - When and how expect to see issues with background synchronization, especially on Samsung devices)
- Last uncaught exception time - Helps clarify if users say “the app is crashing” but actually something else is failing.

Some of these items could have privacy or other implications.  For that reason, we might decide to omit or modify how we collect these.

For example, the current system clock, app install time, update time, etc could be fairly unique.  On the other hand, we can still help with fuzzed information such as "Last updated about 5 days ago". "First installed about 9 months ago".  Then we also won't need the current clock time either.

**Comment by pacu** [comment]
IDEAL: we should let the users choose which items they would like to share with us at the time of the contact.
