### ISSUE TITLE
Prevent Illegal Input in ZEC Send/Request Form

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#218]
### Describe the issue
The ZEC request form prevents non-numeric input but it does not enforce correctly formatted amounts

#### If so, please list the steps to reproduce below:
1. Visit the ZEC request screen
2. Type `1.2.3.4`

Note: this also reproduces on the ZEC send screen

### Expected behaviour
This should be prevented, such that the user can only type 1.234.  A more complex issue is the thousands separator, which also needs to be correctly enforced.

### Actual behaviour + errors
Users are allowed to type 1.2.3.4 which will have unexpected behavior when trying to parse as ZEC into Zatoshi

**Comment by HonzaR** [comment]
Hi @ccjernigan,

I've checked possible solutions here:

- Use method `toDoubleOrNull()`, which helps us with checking the correct use of `.`, but unfortunately does not help us with USA thousand `,` separator. 
- Then the proper way to check number would be using of regex. I've already created one for our purpose `"^[0-9]+([,][0-9]+)?([.][0-9]+)?$"`, which works pretty well, but is built only for USA number formatting patterns. There is also a problem with other locale like Arabic, Chinese, etc.
- Use some of existing solid solution, e.g. `Commons.NumberUtils` (https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/math/NumberUtils.html#isNumber-java.lang.String-)
- There are more solutions available, which don't seem to work with our use case (e.g. https://www.techiedelight.com/determine-string-is-number-kotlin/)

Ideally, we'd like to use some Kotlin build-in validation feature to bypass problems with different number formats in different countries as well as for different alphabets. Do you know some? What would be the way we should go? Thank you.

Here is a quite good source of information, which we need to keep in mind: https://docs.microsoft.com/en-us/globalization/locale/number-formatting

**Comment by ccjernigan** [comment]
In general, we avoid floating point values because of imprecision.  (If absolutely necessary, we might use BigDecimal in a few places).

Since we’re defining our own currency, we have some additional control over the formatting rules.  At the moment, I think we’re mostly just trying to be consistent with the user’s locale for text direction and thousands/decimal separators.

We know what the separators are, extracting them out from the currency localization.  We likewise can get the text direction.

I think a regex solution is probably the most viable.  We might turn the regex into a string template to swap out the position of the comma and period.  That would cover most languages.  Then I suppose we need a different template for RTL languages.

If we put this regex string template in the strings.xml, the default one would cover most languages then we can special case the exceptions with locale-specific additions.

What do you think?
