### ISSUE TITLE
State is Lost During Wallet Backup Flow

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#246]
### Describe the issue
During the wallet backup flow, a configuration change will cause state loss.

#### If so, please list the steps to reproduce below:
1. Clean install the app
2. Create a new wallet
3. Go to the last screen of the wallet backup flow
4. Cause a configuration change (e.g. rotate the screen or switch between light/dark mode)

### Expected behavior
The app restores to the final screen

### Actual behavior + errors
The app restores to the first screen of the backup flow.

**Comment by HonzaR** [comment]
After I've filed the new issue of crashing app - https://github.com/zcash/secant-android-wallet/issues/356 I realized that this could be probably the same problem as described there.

**Comment by HonzaR** [comment]
Closing, this issue is solved in https://github.com/zcash/secant-android-wallet/pull/384.
