### ISSUE TITLE
Design: Privacy & Opt-in/out for cloud services

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#305]
## Is your feature request related to a problem? Please describe.
We have different cloud services that we need to give the user to opt-in or out of.  These would be:
 - #301 
 - #304

## Describe the solution you'd like
1. During onboarding, give the user opt-in/out options for:
    1. Storing secret in Google Credential Manager
    2. Enabling crash analytics
2. In settings, give the user opt-in/out options for 
    1. Storing secret in Google Credential Manager
    2. Enabling crash analytics

My suggestion to implement it as above is primarily based on grouping these opt-in/out prompts together, although other designs that shows them separately is also reasonable depending on what the ultimate designs look like.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/395c45b9-417b-4e7f-9d16-2e373104caa6)

This version was made assuming that the user's choice was to use a cloud service or physically write down (and prove) their backup. Crash analytics currently does not share enough info about the process.

**Comment by HonzaR** [comment]
@geffenz @ccjernigan Thanks for these designs. I have a few thoughts to discuss:

1. Don't we want to have all the consents in one place? I'm in favor of having only one consent screen, which we prompt to user in the onboarding. It might be ideally extendable so we're able to add another service to opt-in/out later (e.g. Google Credentials, Firebase Crashlytics, Firebase Analytics, etc.). I can imagine several switch buttons with descriptions - each for a different service. Most important for us for the first production build are:

   - **Google smart lock** -  For saving the seed phrase. We already have it on the first screen above, maybe just a little naming change: Google Credentials Manager -> Google Smart Lock. And making it shorter for the switch button?
   - **Crashlytics** - This can be probably again only a switch button with a text like: Send anonymous crash reports to our Firebase Crahslytics.
   
2. Or maybe switch buttons are not enough to properly explain to users what we're talking about. So these switch buttons may end up as buttons leading to a separate permission (service) detail screen? 

3. What is the right place for this new screen? A common use-case is to have it as a last page of the onboarding, for example. 

After implementing this new page, we'd be good to use Google Credentials Manager for the saving or restoring of the user seed phrase in _Create new wallet_ or _Restore existing wallet_ flows.

4. The second **Settings screen** seems good to me. May be just a little change to hide the opt-in/out Crash button its own Permission screen so it's not so easy to accidentally switch it off?

**Comment by pacu** [comment]
@geffenz  @ccjernigan I think we can have 2 kinds of UX here.

1. show cloud storage of credentials upfront and delay self custody backup + periodically prompting the user to back up them physically
2. Make the user follow the backup flow as it is currently and then offer to additionally back the keys up in the cloud.

1 favors faster onboarding, while 2 favors self-custody

**Comment by pacu** [comment]
> Crashlytics - This can be probably again only a switch button with a text like: Send anonymous crash reports to our Firebase Crahslytics.


Note: I assume this is more a colloquial thing but we've had negative sentiment on Firebase being shipped with the app. So we opted for open source crash analytics like bugsnag instead.

**Comment by HonzaR** [comment]
Yes @pacu, you're right about the UX types we have here. We've agreed that we better split consents for analytics and credentials to keep them closer to the related use-case. There are also other flows we need to cover with designs, like Restore wallet flow or additional opt-in/out later from Settings, etc. About Firebase, yes, that was just an example, but yea, we probably choose something open-source. Thanks for your thought!

**Comment by HonzaR** [comment]
I'm closing this, as the designs and related implementation tasks are prepared.
