### ISSUE TITLE
[Scaffold] Home Screen Implementation

### ISSUE THREAD

**Issue by pacu** [zcash/secant-android-wallet#308]
# User Stories Involved in the home screen
## Profile Button
As a user I would like to see a page where my user profile is displayed, so that I can see different kind of information related to my wallet

## Send button
As a user I would like to initiate a Zec payment without deciding the source of the recipient, so that I can decide further on how to add a recipient for my transaction

acceptance criteria:
the button navigates to the Send flow placeholder

## Request ZEC button

| As a | I would like to|So that |Acceptance criteria |
| ------ |------ |------ |------ |
|user|create a Payment Request that I can share as a QR code|users with wallets that can read Zec Payment Requests can send me funds easily|Payment request is ZIP-321 compliant|
|user|create a Payment Request that I can share as text URI|I can send that URI through text sharing methods that users can use pay me through that URI|Payment request is ZIP-321 compliant|

when the request zec button is tapped the application should navigate to the request zec flow

## Progress Status

| As	a | I would like to|	So that |	Acceptance criteria |
|------|------|------|------|
|user|see progress in blockheight and % of the sync process|I can be aware that my wallet is doing something and know what to expect|
|user|optimistic synchronization progress|I can know how long might take to sync|
|user|see an offline status if no there's no internet connection|I can know that I'm offline and take action|
|user|see an error state if something went wrong|I can know that and take action|

 
# Final design (for element reference)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/8cc6f1e3-6333-4214-8092-4c8516962db4)

**Comment by geffenz** [comment]
[Uploading... image.png]

**Comment by geffenz** [comment]
Design assets are available here : https://xd.adobe.com/view/a0f26464-5046-472d-a94c-1742462340f5-f5a1/

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/f6c30b67-0e75-462d-8c78-5ced993a4955)

**Comment by geffenz** [comment]
For clarity, scaffolding is all about functionality. Feel free to fully ignore designs and use two [----->50%         ] simple progress bars for the circle dials!
