### ISSUE TITLE
[Scaffold] Progress Status Circular Bar

### ISSUE THREAD

**Issue by pacu** [zcash/secant-android-wallet#310]
| As	a | I would like to|	So that |	Acceptance criteria |
|------|------|------|------|
|user|see progress in blockheight and % of the sync process|I can be aware that my wallet is doing something and know what to expect|
|user|optimistic synchronization progress|I can know how long might take to sync|
|user|see an offline status if no there's no internet connection|I can know that I'm offline and take action|
|user|see an error state if something went wrong|I can know that and take action|

**on the lottie animation**: Make sure that it plays well with the progress calculation so that indicating a % to progress the animation to, matches the circular progress you want, to a avoid bugs and headaches. ^^

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/76835e80-13cf-403c-97c3-f4faafe05a10)

**Comment by geffenz** [comment]
For clarity, scaffolding is all about functionality. Feel free to fully ignore designs and use two [----->50%         ] simple progress bars for the circle dials!

**Comment by HonzaR** [comment]
Hi @geffenz, please, can we have all icons from this [pack](https://xd.adobe.com/view/a0f26464-5046-472d-a94c-1742462340f5-f5a1/grid/) exported? Thank you.
