### ISSUE TITLE
[Scaffold] Full Wallet History

### ISSUE THREAD

**Issue by pacu** [zcash/secant-android-wallet#314]

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/5bc9cf5c-3d92-4e34-a353-8b643c831e97)

**Comment by geffenz** [comment]
Some additional line items discussed as well: ![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/6600d245-2e38-47d6-bf9f-b5e9cad6f322)
