### ISSUE TITLE
[Scaffold] Latest Activity / Transactions Snippet

### ISSUE THREAD

**Issue by pacu** [zcash/secant-android-wallet#316]

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/49e534e5-5805-4d9f-aad7-0df74086b857)

Latest activity is always open on the home or balance screen, If you click all it will scale up to use ~80% of the screen, but should use only around ~25 of the screen when minimized. The ALL button and gesture flicking the drawer up should both change the state to the larger view. Clicking latest or flicking down will reverse this.

The larger view (below) has another ticket for scaffolding.

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/2f2d63a7-cbd2-45b7-bff1-b5bc75d66430)

**Comment by geffenz** [comment]
You can see examples in the Secant Styleguide : https://xd.adobe.com/view/263f30e0-60c2-48c8-8fda-dd40c83686e0-736c/
