### ISSUE TITLE
Design: App Update Dialog

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#339]
In order to implement zcash/zcash-android-wallet-sdk#211, we need a design for the app update dialog.  Because this dialog will be implemented on top of Google Play's app update API, we'll have limited information.  Basically, we'll know an "urgency" value of the update and can decide whether to force the update or allow a user to keep using their current version.

https://developer.android.com/guide/playcore/in-app-updates

**Comment by geffenz** [comment]
The ping for an update could be received a half minute or so into a session (or even later) so assume the screen is already populated. AKA modal solution?

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/007dddac-f74a-4cae-8f90-2a3e64607dab)
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/0549e7b6-7601-41c8-80ad-c00e74663bb2)

I would imagine using the "urgency" value to select one of two screens. There is an edge case here where if they never did a backup (assuming this is possible) we would want to force them to do that flow first.

**Comment by HonzaR** [comment]
Thanks @geffenz for the designs. Yes, the proposed solution with a link to the Play store is a good way to provide more information about changes in the new version and also it's very easy to implement. Users can also update our app from Google Play store right away, if they prefer to.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/ca9d2228-bc6b-4e9d-819c-b010fa6d4f38)

Small tweaks apply.

**Comment by HonzaR** [comment]
@geffenz Thank you, looks good to me. Just one comment on it. We can place the blue link to Google Play Store to both versions of the update screen (available x required). Imho it can be useful on both screens, what do you think?

**Comment by geffenz** [comment]
Absolutely! The only real difference should be whether or not the action is forced. Please!
