### ISSUE TITLE
Add documentation on build variants (testnet and mainnet)

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#362]
## Is your feature request related to a problem? Please describe.
The application is configured for build variants with testnet and mainnet, however no documentation exists to explain the difference between these two variants

## Describe the solution you'd like
 - Add documentation on what the variants are and when one might use them
 - Add documentation on how to switch between the variants in Android Studio
 - Add documentation on how to add funds via the testnet faucet

**Comment by HonzaR** [comment]
Don't forget to mention this also in the other documentation files like `Setup.md`
