### ISSUE TITLE
Check which manifest <queries> do we need to declare

### ISSUE THREAD

**Issue by HonzaR** [zcash/secant-android-wallet#396]
### Describe the issue
Check and test which _manifest_ `<intent>` do we need to declare in `<queries>` to be able to get access to other non-system application (see [documentation](https://developer.android.com/training/package-visibility/declaring)). It seems we should declare at least:

- `<action android:name="android.intent.action.SENDTO"/>` for sending emails.
- `<action android:name="android.intent.action.SEND"/>` for sharing texts
- `<action android:name="android.intent.action.VIEW"/>` e.g. for opening internet browsers and store apps
- etc.

**Comment by ccjernigan** [comment]
I think we're OK on this, because we aren't using the `PackageManager` to scan for other packages.  We're just relying on the system chooser dialog, which shouldn't have a restriction.  Is there another use case that you might be thinking of?

**Comment by HonzaR** [comment]
Yes, you're right. I just commit changes [here](https://github.com/zcash/secant-android-wallet/commit/0ecebe09db9d42f91ec3034ebb820a4af5ebf1e5), which require to have it declared. But I don't think it's the only one way to do it, so we can probably refactor it to get rid of them too. Once I have my changes done, I'll create a PR and we can discuss it there.

**Comment by HonzaR** [comment]
Ok, it turned out that we can do this without declaring the actions in our manifest for now. So I'm closing the issue for now.
