### ISSUE TITLE
Correct Link to Wallet on Website

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#408]
https://electriccoin.co/wallet-resources/

This page links to the old wallet app.  Once this project is ready, the link should change to this repo.

**Comment by geffenz** [comment]
Blocked temporarily by a decision over whether or not we will be sharing the new wallet's styleguide with the public / opensource questions.

**Comment by geffenz** [comment]
(Additional content request from growth/dev)

**Comment by geffenz** [comment]
Corrected!
