### ISSUE TITLE
Robo test blank screens

### ISSUE THREAD

**Issue by HonzaR** [zcash/secant-android-wallet#416]
### Describe the issue
When we enabled the robo test runner to crawl over app screens behind onboarding and its wallet creating or importing, we've found some blank screens in the robo test results. We're not able to replicate this screens state on real or emulator devices for now.

### Actual behavior + errors
There are some blank screens in robo test results. It can be found on Robo tab, in Screenshots or in Video too. E.g. this test shows the problem pretty well [link](https://console.firebase.google.com/u/4/project/android-firebase-b0cf1/testlab/histories/bh.61ab335878181908/matrices/4931527179421692231/executions/bs.6cfe67ee8040b54b/robo).

**Comment by ccjernigan** [comment]
This is just a guess, but we do have issues where clicks are not debounced (#214).  This can cause double-navigation, which can trigger a blank screen.
