### ISSUE TITLE
Reduce Flicker of Sync Status

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#527]
### Describe the issue
The UI flickers briefly when synchronizing.

This is a followup to #310.

#### If so, please list the steps to reproduce below:
1. Create a wallet and watch the home screen
2. Wait about 35 seconds, watching the area around the balance

### Expected behavior
¯\_(ツ)_/¯ 

Not flickering!  In part, we could add a debounce delay before showing the progress indicator.  Implementing that adds another issue, where there wouldn't be an indicator of how fresh the data is.  One option might be to change the text "up-to-date" to reflect changing values.  "Updated less than a minute ago" isn't super helpful, because it still doesn't change during ideal conditions.  "Updated at 12:21pm" might be better, because the value keeps refreshing and providing a user a visual indicator that it actually did something.

### Actual behavior + errors
The app is behaving "correctly" in that it shows a loading state while making a request to the server.  The problem is that when requests occur very quickly, the UI appears to flicker as the indicator displays and then disappears.

**Comment by ccjernigan** [comment]
Assigning to geffenz to get some clarity on what the actual behavior should be.

**Comment by geffenz** [comment]
Subtitles like "up-to-date" don't change unless there is a problem, create a more interactive subtitle or "last updated xx:xx"

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/5f2fa232-d4c5-4364-99f8-fd55e1f448e6)

The final home screen design has a circular widget that contained the ability to show multiple sync states (and action states).

However, the current MVP may be able to use a more clear double progress bar or simplified your_height/tip_height status.
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/3b16e07a-4b27-47de-a5bf-1922315e8388)

This is an ongoing discussion right now with syncing optimizations to handle tx spam.

**Comment by geffenz** [comment]
Closing. Will reopen if necessary during design reviews.
