### ISSUE TITLE
Consider replacing Zboto Font with Icon

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#528]
## Is your feature request related to a problem? Please describe.
To show the ZEC currency symbol, we currently use a custom font with the $ symbol swapped out.  While this works, it adds bloat to the app size.  It is also difficult for someone new to the codebase to understand, since the symbol is hidden inside a font with a single character change.

## Describe the solution you'd like
Use a single vector graphic and a custom Compose layout to align the ZEC symbol with the numeric text.

**Comment by geffenz** [comment]
Considered, we are doing it. There is another ticket for the asset delivery.
