### ISSUE TITLE
Figure out the top bar on Android's onboarding

### ISSUE THREAD

**Issue by gasstan** [zcash/secant-android-wallet#604]
## Is your feature request related to a problem? Please describe.
Figure out wether to keep top app bar in the onboarding flow. Having top app bar + skip/back buttons separately takes a lot of screen space.

## Describe the solution you'd like
 If the design called for a bar with a standard Android back button, title, and then a skip button E.g. <- Zcash Skip then that would improve the screen height.

**Comment by ccjernigan** [comment]
After conversation with Geffen, we can use the standard Android titlebar with the back arrow which will give us some space back on the onboarding screens.

This was already implemented, we have a boolean constant in the onboarding flow that will let you toggle between the two modes.  So we can leverage the existing code (and probably remove the boolean condition entirely).
