### ISSUE TITLE
Figure out design for background behind the bottom buttons

### ISSUE THREAD

**Issue by gasstan** [zcash/secant-android-wallet#605]
## Is your feature request related to a problem? Please describe.
With scrolling added to the screens, the content is overflowing under the footer buttons which looks really bad

## Describe the solution you'd like
We should add background for the footer layout.

## Additional context
![image](https://user-images.githubusercontent.com/5649403/193567674-14919ada-5894-41fd-9e16-38792c573511.png)

**Comment by ccjernigan** [comment]
@geffenz Although we're going to fix the image scaling, there might be some devices that still are too large (or maybe in horizontal layout).  How would you like the UI to handle when the text is larger than the screen?  Should the text stop above the next button, rather than scrolling behind it?

**Comment by geffenz** [comment]
Yeah, so the original design had no header and back/skip buttons floating over the image. As we are doing an MVP in just material design, I believe the steps here would be:

1. Put the arrow (<-) in the header for back and skip on the right side (this is the small app bar as defined by m3).
2. No padding before the image and have it use 80% width of the content area.
3. No padding after image.
4. Font sizes will probably need to change, possibly responsively. I can start working on this in the theme (type.kt).
5. Yes, let's not let the text scroll behind the next button. Either make them in the same content block or stop overflow behind the next button and padding.

I'm going to make an updated images folder with the restore/backup images too. @ccjernigan you mentioned scaling issues with them. Is this something I can fix by rescaling them prior to embedding?
