### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by ccjernigan** [zcash/secant-android-wallet#766]

**Comment by HonzaR** [comment]
@geffenz please, may I ask you for the icon resources, as we discussed on the last meeting? Thank you.

**Comment by geffenz** [comment]
Yep, everything you should need including the -night version is here:  https://www.dropbox.com/s/t9sd6ubl9o9q7ti/res-mainnet.zip?dl=1
![ic_launcher-playstore](https://user-images.githubusercontent.com/47196503/225053015-76c25411-707f-479f-9a59-41995588a5e6.png)
