### ISSUE TITLE
Update Github secrets to re-enable deploying to Google Play from CI

### ISSUE THREAD

**Issue by HonzaR** [zcash/secant-android-wallet#935]
We need to set re-generated Google Play transfer keys to the Github Secrets to be able to deploy from our CI again. 

The screenshot below shows what our CI deployment action expects to find in the Github Secrets. 

![Snímek obrazovky 2023-08-07 v 15 44 41](https://github.com/zcash/secant-android-wallet/assets/9017390/d8c6c154-afba-4878-be63-e2eb59c64f2f)

According to our latest communication with @nick-ecc we have these keys. We need to use them in the GitHub Secrets.

Otherwise, our deployment to Google Play is blocked by the deploying failure. See last month's deploying results:
https://github.com/zcash/secant-android-wallet/actions/workflows/deploy.yml

Github Secrets [documentation](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

**Comment by nuttycom** [comment]
This should now be resolved; we can mark it as closed once we've actually completed a release using these secrets!

**Comment by HonzaR** [comment]
@nuttycom After our latest changes, it seems like we are facing another problem. Previously it was:
```
"message": "The Android App Bundle was signed with the wrong key. Found: SHA1: X, expected: SHA1: Y"
"status": "PERMISSION_DENIED"
```
And it's:
```
base64: invalid input
```

**Comment by HonzaR** [comment]
The problem could be in the Google Play publisher plugin we use. See https://github.com/Triple-T/gradle-play-publisher. The plugin also started conflicting with the crash deobfuscation upload from Bugsnag, and the plugin maintainer says he’s not working on it anymore.

Possible solutions are:
- Switch to a different, similarly working Gradle plugin
- Rework deployment to use the Google Java API directly
   - It would require changing the version number incrementing to a different strategy, e.g., maybe using a number of git commits as a monotonically increasing number. It still could be queried from the Play Store, but we're thinking about simplicity so that the only API call that has to be made is the upload. We also need to look up jgit and we have to change the GitHub checkout fetch depth.

**Comment by HonzaR** [comment]
The GitHub secrets and variables are set correctly, but we must still resolve its follow-up #992.
