### ISSUE TITLE
Core BTS UI: Load Screen

### ISSUE THREAD

**Issue by nuttycom** [zcash/secant-android-wallet#941]
Update the loading screen to a transition between the following views:
 
- [ ] https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=88%3A4814&mode=design&t=9FayedV7L5uAZNyV-1 
- [ ] https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=88%3A4551&mode=design&t=9FayedV7L5uAZNyV-1 
- [ ] https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=88%3A4443&mode=design&t=9FayedV7L5uAZNyV-1

**Comment by HonzaR** [comment]
For refactoring the Splash screen, you need to change the `ui-lib/src/main/res/ui/common/values/themes.xml`. Then there are necessary changes required to align with the new screen UI. Related components are:
- `ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/ShortOnboardingView.kt`
- `ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/view/LongOnboardingView.kt`

The transition from the dark to light, and vice versa, will be the trickiest part.

#### See the current screen state:
<img src="https://github.com/zcash/secant-android-wallet/assets/9017390/b978482f-a82f-48e9-9122-1df2f0d21efa" width="300" /><img src="https://github.com/zcash/secant-android-wallet/assets/9017390/f7767079-2975-403d-a22f-8d382a171689" width="300" />

**Comment by Venkat-corebts** [comment]
LongOnboardingView and ShortOnboardingView will have same UI according to new design ?

**Comment by HonzaR** [comment]
Hi @Venkat-corebts, We can now only focus on the short version of different screens. Also, a new requirement says we should consider the light theme only for now. The dark theme will be prepared later.
