### ISSUE TITLE
Core BTS UI: Settings Screen

### ISSUE THREAD

**Issue by nuttycom** [zcash/secant-android-wallet#948]
Update the "Settings" screen to conform to https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI-082123-V3?type=design&node-id=149%3A7965&mode=design&t=MuSYkgngwcFg2nNl-1

**Comment by Venkat-corebts** [comment]
Hi @HonzaR Are we need to remove the existing code related to functionalities on settings screen or just need to comment out those parts for now as some of them are dependent with home screen logic

**Comment by HonzaR** [comment]
Settings screen UI implemented as part of this PR https://github.com/zcash/secant-android-wallet/pull/958.
